# Generated by Django 4.2.1 on 2023-05-15 17:51

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0017_desporto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='static/parceiros/', variations={}),
        ),
    ]
