# Generated by Django 4.2.1 on 2023-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_pessoa/')),
                ('nome', models.CharField(max_length=200)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('linkedin', models.CharField(blank=True, max_length=200)),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField(max_length=500)),
            ],
        ),
    ]
