# Generated by Django 4.2.1 on 2023-05-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data_adicao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='texto',
        ),
    ]
