# Generated by Django 4.2.1 on 2023-05-14 11:13

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0002_remove_pessoa_data_adicao_remove_pessoa_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='fotos_pessoa/', variations={}),
        ),
    ]
