# Generated by Django 4.2.1 on 2023-05-14 14:41

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0005_parceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='static/fotos_pessoa/', variations={'thumbnail': {'height': 300, 'width': 300}}),
        ),
    ]
