# Generated by Django 4.2.1 on 2023-05-15 08:00

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0010_alter_video_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='static/parceiros/', variations={'thumbnail': {'crop': True, 'height': 120, 'width': 220}}),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='static/fotos_pessoa/', variations={'thumbnail': {'crop': True, 'height': 300, 'width': 300}}),
        ),
        migrations.AlterField(
            model_name='video',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='static/videothumbs/', variations={'thumbnail': {'crop': True, 'height': 220, 'width': 380}}),
        ),
    ]
