# Generated by Django 4.2.1 on 2023-05-15 08:06

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0011_alter_parceiro_imagem_alter_pessoa_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='static/videothumbs/', variations={'thumbnail': {'crop': True, 'height': 10, 'width': 10}}),
        ),
    ]
