# Generated by Django 4.2.1 on 2023-05-15 17:11

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0014_video_data_adicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='static/noticiathumbs/', variations={})),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
