# Generated by Django 4.2.1 on 2023-05-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0015_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
