# Generated by Django 4.2.1 on 2023-05-15 17:48

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0016_alter_noticia_link_alter_noticia_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='static/desportothumbs/', variations={})),
                ('titulo', models.CharField(max_length=200)),
                ('descricao1', models.TextField(blank=True)),
                ('descricao2', models.TextField(blank=True)),
            ],
        ),
    ]
