# Generated by Django 4.2.1 on 2023-05-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0021_remove_email_texto_email_email_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email_list',
        ),
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
