# Generated by Django 4.2.1 on 2023-05-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0022_remove_email_email_list_email_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
