# Generated by Django 4.2.1 on 2023-05-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0023_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
