# Generated by Django 4.2.1 on 2023-05-17 07:11

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0025_alter_email_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='static/fotos/', variations={})),
                ('titulo', models.CharField(max_length=200)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
