# Generated by Django 4.2.1 on 2023-05-17 07:45

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ondacertaradio', '0026_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='foto',
        ),
        migrations.AddField(
            model_name='foto',
            name='imagem',
            field=stdimage.models.StdImageField(default=1, force_min_size=False, upload_to='static/fotothumbs/', variations={}),
            preserve_default=False,
        ),
    ]
